<!-- ---------------------------------------------------- -->
  <div class="col-sm-3 col-md-3 col-lg-3">
	<!-- logo -->  
    <div class="img-responsive">
      <img src="https://res.cloudinary.com/eventro/image/upload/v1668122125/image001.png" width="500" title="Python Avanzado Grupolotal" alt="Curso Python Avanzado">    
    </div>
	<!-- logo -->	
  </div>
<!-- ---------------------------------------------------- --> 
  <div class="col-sm-6 col-md-6 col-lg-6">
	<!-- Pandas Tutorial -->  
	  <center>
	    <br>
        <h1>Dia 3</h1>
 <h1>3.1 Numpy</h1>
        <br>
        <br>
        <strong> Python Avanzado </strong> 
         <br>
        <strong>Alejandro Marcano Van Grieken</strong>
	  </center>	
    <!-- Pandas Tutorial -->	
  </div>
<!-- ---------------------------------------------------- -->

En esta sección aprenderemos:

* El array multidimensional ndarray
* Creación de arrays
* Tipos de datos
* Funciones
* Indexado y selección
* Redimensionamiento de arrays
* Ordenación de arrays
* Operaciones con arrays
* Funciones universales
* Funciones matemáticas


In [2]:
import numpy as np

NumPy da solución, entre otras cosas, a la necesidad de operar con colecciones de valores de una forma eficiente. Así, por ejemplo, si partimos de las siguientes listas:



In [3]:
m = [1, 2, 3]

n = [3, 4, 5]

In [4]:
m + n

[1, 2, 3, 3, 4, 5]

## el array multidimensional (o simplemente array)

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
b = np.array([5, 6, 7])
b

array([5, 6, 7])

In [7]:
a + b

array([ 6,  8, 10])

## Creación de Arrays

La función numpy.array es la forma más simple de crear un array a partir de un iterador como una simple lista (el iterador también puede ser otro array NumPy)

In [22]:
lista = [5, 8, 9, 11]
array_numpy = np.array(lista)

In [23]:
array_numpy.ndim

1

In [24]:
array_numpy.shape

(4,)

In [25]:
array_numpy.dtype

dtype('int32')

## Tipos de Datos

In [26]:
lista2 = [5, 8, 9, 11]
array_numpy2 = np.array(lista2, dtype="float16")

In [27]:
array_numpy2.dtype

dtype('float16')

In [29]:
lista3 = [5.0, 8, 9, 11]
array_numpy3 = np.array(lista3)
array_numpy3.dtype

dtype('float64')

## Array de Dos Dimensiones

In [39]:
matrix = [[4,5,6],[7,8,9]]
matrixnp = np.array(matrix)
matrixnp

array([[4, 5, 6],
       [7, 8, 9]])

## Array de Tres Dimensiones

In [47]:
tres_dimensiones = [[[1,2,3],[4,5,6],[7,8,9]], [[3,2,1],[6,5,4],[9,8,7]]]
tres_dimensiones_np = np.array(tres_dimensiones)
print('Esta es la dimensión',tres_dimensiones_np.shape)

print(tres_dimensiones_np)


Esta es la dimensión (2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]]


## Funciones


### arange
genera un conjunto de números entre un valor de inicio y uno final

In [50]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones
generan arrays de ceros y unos

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones(3)

array([1., 1., 1.])

In [54]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace y logspace


La función numpy.linspace genera un array NumPy formado por n números equiespaciados entre dos dados. Su sintaxis es:

In [59]:
m = np.linspace(10, 40, 4)
m

array([10., 20., 30., 40.])

In [60]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

De forma semejante, la función numpy.logspace genera un array NumPy formado también por n números entre dos dados, pero en una escala logarítmica

In [64]:
m = np.linspace(0, 10, 50)
m

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random 

Hay varias maneras de crear arrays random en numpy
* rand
* randn
* randint

In [65]:
np.random.rand(2)

array([0.54647704, 0.41244569])

In [66]:
np.random.rand(5,5)

array([[0.12628168, 0.51160187, 0.89593384, 0.74011566, 0.0040356 ],
       [0.64422746, 0.59082849, 0.58139361, 0.99065143, 0.40763318],
       [0.64897519, 0.9832185 , 0.11036403, 0.56217402, 0.22007203],
       [0.34056461, 0.41188813, 0.15111731, 0.7606708 , 0.29817306],
       [0.2076955 , 0.20020142, 0.57011624, 0.25162071, 0.22145724]])

In [67]:
np.random.randn(5,5)

array([[-0.28692879, -0.02478261, -0.59103733,  1.4171791 ,  1.2600291 ],
       [ 0.30140116, -1.11126563, -0.13741151, -0.18550174,  0.79377515],
       [-0.71857403,  0.14475225,  1.24769914, -0.72318321,  2.1289046 ],
       [ 0.58117754, -0.31914541, -0.31009327, -0.70151936, -0.51928262],
       [ 0.88589081,  0.11794974,  2.20502122, -0.90995679,  0.26288603]])

In [69]:
np.random.randint(1,100)

5

## Reshape
Contiene un array con la misma data pero nuevas dimensiones

In [71]:
random_array = np.random.randint(0,50,10)
random_array

array([41, 17,  5, 43,  2,  2, 49,  3, 48, 31])

In [77]:
random_array.reshape(2,5)

array([[41, 17,  5, 43,  2],
       [ 2, 49,  3, 48, 31]])

## Flatten

El método numpy.ndarray.flatten devuelve una copia del array multidimensional a una única dimensión.

In [172]:
random_array.flatten()

array([41, 17,  5, 43,  2,  2, 49,  3, 48, 31])

## Transposición

La transposición de arrays es una forma especial de redimensionamiento. 

In [178]:
random_array = np.array([[41, 17,  5, 43,  2],
       [ 2, 49,  3, 48, 31]])
print(random_array)
print('Dimensiones: ',random_array.shape)

[[41 17  5 43  2]
 [ 2 49  3 48 31]]
Dimensiones:  (2, 5)


In [179]:
random_array = random_array.transpose()
print(random_array)
print('Dimensiones: ',random_array.shape)

[[41  2]
 [17 49]
 [ 5  3]
 [43 48]
 [ 2 31]]
Dimensiones:  (5, 2)


## Ordenamiento de arrays

In [185]:
np.sort(random_array)

array([[ 2, 41],
       [17, 49],
       [ 3,  5],
       [43, 48],
       [ 2, 31]])

In [186]:
np.sort(random_array, axis = 0)

array([[ 2,  5],
       [ 2, 31],
       [ 3, 41],
       [17, 48],
       [43, 49]])

## max,min,argmax,argmin
Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar sus ubicaciones de índice usando argmin o argmax


In [73]:
random_array.max()

49

In [74]:
random_array.min()

2

In [75]:
ranarr.argmax()

6

In [76]:
ranarr.min()

1

In [78]:
ranarr.argmin()

9

## Indexando y Seleccionando Datos

### Arrays de una dimensión

In [79]:
random_array

array([41, 17,  5, 43,  2,  2, 49,  3, 48, 31])

In [80]:
random_array[8]

48

In [163]:
random_array[0:3]

array([41, 17,  5])

In [152]:
random_array2 = np.arange(20)
random_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [159]:
random_array2[12:1:-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [160]:
random_array2[12:1:-2]

array([12, 10,  8,  6,  4,  2])

In [156]:
random_array2[2:12:-2]

array([], dtype=int32)

### Matrices o Array de dos dimensiones

In [82]:
matriz = np.array(([5,15,15],[20,25,30],[35,40,45]))
matriz

array([[ 5, 15, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
matriz[2]

array([35, 40, 45])

In [86]:
matriz[2][1]

40

In [89]:
matriz[:,2]

array([15, 30, 45])

In [97]:
matriz[:1,1:]

array([[15, 15]])

 Seleccionando filas no consecuntivas

In [171]:
matriz[[2,0]]

array([[35, 40, 45],
       [ 5, 15, 15]])

## Editar array unidimensional

In [164]:
random_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [166]:
random_array2[2:4] = [5,16]

In [167]:
random_array2

array([ 0,  1,  5, 16,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Condiciones de Selección

In [114]:
array_par = np.arange(2,20, 2)
array_par

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [115]:
array_par > 8

array([False, False, False, False,  True,  True,  True,  True,  True])

In [116]:
array_par >= 8

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [117]:
condicion = array_par >= 8

In [118]:
array_par[condicion]

array([ 8, 10, 12, 14, 16, 18])

## Operaciones con Numpy

## Aritméticas


In [132]:
array1 = np.arange(0,10)
array2 = np.array([4,5,6,4,8,9,7,2,4,7])
print(array1)



[0 1 2 3 4 5 6 7 8 9]
[4 5 6 4 8 9 7 2 4 7]


In [133]:
array1 + array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
array1 + array2

array([ 4,  6,  8,  7, 12, 14, 13,  9, 12, 16])

In [135]:
array1 * array1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [136]:
array1 - array1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
array1 / array2

array([0.        , 0.2       , 0.33333333, 0.75      , 0.5       ,
       0.55555556, 0.85714286, 3.5       , 2.        , 1.28571429])

## Operaciones con escalares

In [188]:
array1 + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [189]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [190]:
array1 % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

## Universal Array Funciones



Una función universal (o ufunc) es una función que opera en arrays NumPy elemento por elemento. La vectorización es la capacidad de operar simultáneamente sobre todos los elementos de un array.  Vamos a mostrar algunos comunes:


La función numpy.sqrt devuelve la raíz cuadrada de los valores de la estructura de entrada:



In [139]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

La función numpy.square devuelve el cuadrado de los elementos de la estructura de entrada:



In [203]:
np.square(array)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

La función numpy.exp calcula la exponencial de los elementos de la estructura de entrada:



In [140]:
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

La función numpy.log devuelve el logaritmo neperiano o natural de los elementos de la estructura de entrada:



In [142]:
np.log(array)

C:\Users\alema\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [198]:
a = np.array([1,3,4,5])
b = np.array([4,7,8,9])

In [199]:
print(np.add(a,b))

[ 5 10 12 14]


In [201]:
print(np.subtract(a,b))

[-3 -4 -4 -4]


In [202]:
print(np.multiply(a,b))

[ 4 21 32 45]


## Funciones Matemáticas

Numpy incluye un conjunto de funciones matemáticas y estadísticas que pueden ser aplicadas a todo un array, a una dimensión de un array o a varias dimensiones de un array

In [209]:
vector = np.arange(1,28).reshape(3,3,3)
vector

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [211]:
np.mean(vector)

14.0

In [212]:
np.mean(vector, axis= 0)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [213]:
np.mean(vector, axis= 1)

array([[ 4.,  5.,  6.],
       [13., 14., 15.],
       [22., 23., 24.]])

In [214]:
np.median(vector)

14.0

In [215]:
np.std(vector)

7.788880963698615

In [216]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
np.cumsum(array)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)